okokok

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,11 +75,22 @@ jobs:
           git push origin main
      
       - name: Run Tests
+        env:
+            DATABASE_URL: ${{ secrets.DATABASE_URL }}
+            SECRET_KEY: ${{ secrets.SECRET_KEY }}
         run: |
             docker compose up -d  # Start containers
             echo "Waiting for application to start..."
+            RETRIES=0
+            MAX_RETRIES=24  # roughly 2 minutes if sleep 5 seconds each
             until curl --fail --max-time 120 http://localhost:5000; do
               echo "Waiting for application to start..."
               sleep 5
+              RETRIES=$((RETRIES+1))
+              if [ $RETRIES -ge $MAX_RETRIES ]; then
+                echo "Application failed to start in time."
+                exit 1
+              fi
             done
             echo "Application started successfully!"
+  
